"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import { config } from "@fortawesome/fontawesome-svg-core";
import Footer from "../components/footer";
import { useRouter, usePathname, useSearchParams } from "next/navigation";
// import { useRouter } from "next/router";
// import "@fortawesome/fontawesome-free/css/all.css";

// Prevent automatic CSS injection by Font Awesome
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Daniel Adonis Nnaoma",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const pathname = usePathname();
  // const usesearchparams = useSearchParams();

  const isAdmin = pathname.startsWith("/admin");
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="containers w-full">
          {!isAdmin && (
            <header>
              <Navbar />
            </header>
          )}
          <main>{children}</main>
          {!isAdmin && <Footer />}
        </div>
      </body>
    </html>
  );
}
