import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// import Navbar from "../components/navbar";
import NewNav from "../components/newNav";
import { config } from "@fortawesome/fontawesome-svg-core";
import Footer from "../components/footer";
// import "@fortawesome/fontawesome-free/css/all.css";

// Prevent automatic CSS injection by Font Awesome
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nart The Designer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="containers w-full">
          <header>
            <NewNav />
            {/* <NavbarNew /> */}
            {/* <Navbar /> */}
          </header>
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
