"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "../components/navbar";
import { config } from "@fortawesome/fontawesome-svg-core";
import Footer from "../components/footer";
import { useRouter, usePathname, useSearchParams } from "next/navigation";
// import { useRouter } from "next/router";
// import "@fortawesome/fontawesome-free/css/all.css";

// Prevent automatic CSS injection by Font Awesome
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Daniel Adonis Nnaoma",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();
  const pathname = usePathname();
  // const usesearchparams = useSearchParams();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-full">
          <header className="fixed h-16 top-0 left-0 w-full z-10 px-4 py-4 text-xl text-center font-br-firma-medium tracking-tighter bg-white border-b-2 border-gray-800">
            <Link href="/" className="">
              Daniel Adonis
            </Link>
            {/* <Navbar /> */}
          </header>
          <main>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
